#!/usr/bin/env python3
"""Rasterize the NOVA component bible's two density classes (licensed OFL fonts)."""
import hashlib,json
from pathlib import Path
from PIL import ImageFont
ROOT=Path(__file__).resolve().parents[1]
src=ROOT/'lib/PortableApps/home_fonts';out=ROOT/'Services/scene_host/fonts'
faces=[('title',13,'Orbitron-reference-700.ttf'),('section',9,'Orbitron-reference-700.ttf'),('body',14,'Rajdhani-600.ttf'),('small',10,'Rajdhani-600.ttf'),('value',28,'Orbitron-reference-700.ttf'),('tab',8,'Orbitron-reference-700.ttf')]
rows=['/* Generated by generate_scene_component_fonts.py; SIL OFL-1.1. */'];manifest=[]
for density in (1,2):
 for role,size,file in faces:
  if density==2 and file=='Rajdhani-600.ttf':file='Rajdhani-700.ttf'
  f=ImageFont.truetype(str(src/file),size*density);ident=f'nova_{role}_{density}';glyph=[]
  for cp in range(32,127):
   mask,offset=f.getmask2(chr(cp),mode='L',anchor='ls');w,h=mask.size;bits=bytearray((w*h+7)//8 or 1)
   for i,v in enumerate(mask):
    if v>=128:bits[i//8]|=128>>(i%8)
   symbol=ident+'_'+str(cp);rows.append('static const uint8_t '+symbol+'[]={'+','.join(map(str,bits))+'};')
   glyph.append('{%d,%d,%d,%d,%d,%s}'%(w,h,*offset,round(f.getlength(chr(cp))*64),symbol))
  rows.append('static const pc_glyph '+ident+'_glyphs[]={'+','.join(glyph)+'};')
  rows.append('static const pc_font '+ident+'={'+ident+'_glyphs,NULL,0};')
  manifest.append({'font':file,'size':size*density,'role':role,'density':density,'sha256':hashlib.sha256((src/file).read_bytes()).hexdigest()})
(out/'components.inc').write_text('\n'.join(rows)+'\n')
(out/'COMPONENT-SOURCES.json').write_text(json.dumps({'license':'SIL OFL-1.1','fonts':manifest,'threshold':128},indent=2)+'\n')
