#!/usr/bin/env python3
"""Losslessly adapt frozen Reader spans to C; generate bounded Q20 dial table.

The original generator and input/font identities are recorded beside the assets.
This conversion never re-rasterizes fonts and needs only Python's stdlib.
"""
import argparse
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'lib/PortableApps/desk_clock'
SOURCE = ROOT / 'test/fixtures/desk_clock_reader/DeskClockDigits.h'


def outputs():
    source = SOURCE.read_text()
    substitutions = {
        '// Generated by scripts/generate_clock_digits.py; do not edit.':
        '/* Numeral spans transcribed byte-for-byte from the frozen Reader asset.\n'
        ' * Generated C form: scripts/generate_desk_clock_assets.py. */',
        '// Noto Sans / Noto Serif: SIL Open Font License, see builtinFonts/source.':
        '/* Noto Sans / Noto Serif: SIL OFL; see LICENSE-NotoSans/Serif.txt. */',
        '#pragma once\n#include <cstdint>\nnamespace DeskClockDigits {\n': '',
        'struct Span { uint8_t y, x, width; };': 'typedef struct { uint8_t y, x, width; } DeskSpan;',
        'struct Glyph { uint16_t start, count; uint8_t width; };':
        'typedef struct { uint16_t start, count; uint8_t width; } DeskGlyph;',
        'constexpr int height = 224;': 'enum { DESK_DIGIT_HEIGHT = 224 };',
        'constexpr Span': 'static const DeskSpan',
        'constexpr Glyph': 'static const DeskGlyph',
        '}  // namespace DeskClockDigits\n': '',
    }
    for old, new in substitutions.items():
        assert old in source, old
        source = source.replace(old, new)
    values = [round(math.sin(i * math.pi / 360) * (1 << 20)) for i in range(181)]
    table = ['/* Generated half-degree quarter-wave sine, Q20. No on-device libm. */',
             'static const int32_t desk_sine_q20[181] = {']
    table += ['    ' + ', '.join(map(str, values[i:i+10])) + ',' for i in range(0, 181, 10)]
    table += ['};', '']
    return {'digits.inc': source, 'sine.inc': '\n'.join(table)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in outputs().items():
        path = ASSETS / name
        if args.check:
            assert path.read_text() == content, f'{path} is stale'
        else:
            path.write_text(content)
    print('Desk-clock assets: frozen spans and half-degree Q20 table verified')
