#!/usr/bin/env python3
"""Generate bounded alpha masks; offline Pillow + Inkscape only.
No fonts, SVG parser, floating point, or allocation in firmware.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import struct, math, subprocess, tempfile, hashlib, json
ROOT = Path(__file__).resolve().parents[1] / 'lib/PortableApps'
F = ROOT / 'quick_fonts'
alpha=[]
lines=['/* Generated by generate_assets.py. See quick_fonts/SOURCES.json and font licenses. */']
def array(name, type_, vals, n=20):
    return '\n'.join([f'static const {type_} {name}[] = {{'] + ['  '+','.join(str(v) for v in vals[i:i+n])+',' for i in range(0,len(vals),n)] + ['};'])
def add(im):
    offset=len(alpha); alpha.extend(im.tobytes()); return offset
for name, file, size, chars, tracking in [
    ('time','Orbitron-700.ttf',13,'0123456789:-APM ',.78),
    ('percent','Orbitron-700.ttf',10,'0123456789%!-',0),
    ('label','Rajdhani-600.ttf',10,'ABCDEFGHIJKLMNOPQRSTUVWXYZ -',.72),
    ('caption','Rajdhani-600.ttf',9,'ABCDEFGHIJKLMNOPQRSTUVWXYZ -',.55),
    ('torch','Rajdhani-600.ttf',11,'TAP TO TURN OFF',2.2)]:
    font=ImageFont.truetype(str(F/file),size*4)
    glyphs=[]
    for c in sorted(set(chars)):
        box=font.getbbox(c,anchor='ls')
        l=math.floor(box[0]/4)-1;t=math.floor(box[1]/4)-1
        r=math.ceil(box[2]/4)+1;b=math.ceil(box[3]/4)+1
        im=Image.new('L',((r-l)*4,(b-t)*4))
        ImageDraw.Draw(im).text((-l*4,-t*4),c,fill=255,font=font,anchor='ls')
        im=im.resize((r-l,b-t),Image.Resampling.LANCZOS)
        offset=add(im)
        advance=round((font.getlength(c)/4+tracking)*256)
        glyphs.append(f'{{{ord(c)},{l},{t},{im.width},{im.height},{advance},{offset}}}')
    lines.append(array('pqa_'+name+'_glyphs','pqa_glyph',glyphs,3))

p=(F/'FAClassicSolid_18.cpfont').read_bytes()
assert p[:8]==b'CPFONT\0\0' and struct.unpack_from('<H',p,8)[0]==4
_,intervals,count,advance,asc,desc,kl,kr,klc,krc,lig,base=struct.unpack_from('<B3xIIBhhHHBBBI4x',p,32)
glyphbase=base+intervals*12
bitmapbase=glyphbase+count*16+kl*3+kr*3+klc*krc+lig*8

def cpfont(cp, side):
    index=None
    for j in range(intervals):
        a,b,o=struct.unpack_from('<III',p,base+j*12)
        if a<=cp<=b:index=o+cp-a;break
    assert index is not None,hex(cp)
    w,h,_,_,_,length,offset=struct.unpack_from('<BBHhhH2xI',p,glyphbase+index*16)
    packed=p[bitmapbase+offset:bitmapbase+offset+length]
    im=Image.new('L',(w,h));im.putdata([(packed[i//4]>>(6-2*(i%4))&3)*85 for i in range(w*h)])
    factor=side/max(w,h)
    return im.resize((round(w*factor),round(h*factor)),Image.Resampling.LANCZOS)
icons=[]
mapping=[('sun',0xf185,16),('volume',0xf028,16),('muted',0xf6a9,16),('silent',0xf1f6,18),('dnd',0xf186,18),('airplane',0xf072,18),('wifi',0xf1eb,18),('torch',0xf0eb,18)]
for name,cp,side in mapping:
    im=cpfont(cp,side);icons.append((name,im))
with tempfile.TemporaryDirectory() as tmp:
    target=Path(tmp)/'bt.png'
    subprocess.run(['inkscape',str(F/'bluetooth-b.svg'),'--export-type=png','--export-width=36','--export-height=72',f'--export-filename={target}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    im=Image.open(target).convert('RGBA').getchannel('A').resize((9,18),Image.Resampling.LANCZOS)
    icons.append(('bluetooth',im))
for name,im in icons:
    lines.append(f'static const pqa_icon pqa_icon_{name} = {{{im.width},{im.height},{add(im)}}};')
lines.append(array('pqa_alpha','uint8_t',alpha,28))
(ROOT/'src/quick_actions_assets.inc').write_text('\n'.join(lines)+'\n')
manifest={
    'description':'NOVA-7 original Orbitron/Rajdhani and genuine Font Awesome masks, renamed PortableQuickActionsAssets.',
    'fontawesome_commit':'14c65a3747d0f3b751f15831fc719236aea8729d',
    'fontawesome_font_license':'SIL OFL 1.1; FAClassic-LICENSE.txt',
    'bluetooth_icon_license':'CC BY 4.0; attribution Fonticons, Inc. See FAClassic-LICENSE.txt.',
    'bluetooth_source':'https://github.com/FortAwesome/Font-Awesome/blob/14c65a3747d0f3b751f15831fc719236aea8729d/svgs/brands/bluetooth-b.svg',
    'orbitron_source':'Watch/apps/clock/nova/fonts/Orbitron-700.ttf; SIL OFL 1.1',
    'rajdhani_source':'Watch/apps/clock/nova/fonts/Rajdhani-600.ttf; SIL OFL 1.1',
    'cpfont_source':'Reader SD_fonts/FAClassicSolid/FAClassicSolid_18.cpfont',
    'icons':{name:hex(cp) for name,cp,side in mapping},
    'torch_equivalent':'Font Awesome Free lightbulb (the Free font has no flashlight glyph).',
    'sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(F.iterdir()) if p.name!='SOURCES.json'},
    'assets_sha256':hashlib.sha256((ROOT/'src/quick_actions_assets.inc').read_bytes()).hexdigest(),
}
(F/'SOURCES.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(f'{len(alpha)} alpha bytes; {(ROOT/"src/quick_actions_assets.inc").stat().st_size} source bytes')
